=== reallifedeveloper/rld-common/src/test/resources/dbunit/rld-common.dtd
<!ELEMENT dataset (
    message_tracker*,
    stored_event*)>

<!ELEMENT message_tracker EMPTY>
<!ATTLIST message_tracker
    id CDATA #REQUIRED
    last_published_message_id CDATA #REQUIRED
    publication_channel CDATA #REQUIRED
>

<!ELEMENT stored_event EMPTY>
<!ATTLIST stored_event
    stored_event_id CDATA #REQUIRED
    event_body CDATA #REQUIRED
    event_type CDATA #REQUIRED
    occurred_on CDATA #REQUIRED
    version CDATA #REQUIRED
>

=== reallifedeveloper/rld-common/src/test/resources/dbunit/stored_event.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "rld-common.dtd">
<dataset>

    <stored_event stored_event_id="1" event_type="foo1" event_body="bar1"
        occurred_on="2014-06-07 13:52:00" version="2" />
    <stored_event stored_event_id="2" event_type="foo2" event_body="bar2"
        occurred_on="2014-06-07 13:52:01" version="2" />
    <stored_event stored_event_id="3" event_type="foo3" event_body="bar3"
        occurred_on="2014-06-07 13:52:02" version="2" />
    <stored_event stored_event_id="4" event_type="foo4" event_body="bar4"
        occurred_on="2014-06-07 13:52:03" version="2" />
    <stored_event stored_event_id="5" event_type="foo5" event_body="bar5"
        occurred_on="2014-06-07 13:52:04" version="2" />
    <stored_event stored_event_id="6" event_type="foo6" event_body="bar6"
        occurred_on="2014-06-07 13:52:05" version="2" />
    <stored_event stored_event_id="7" event_type="foo7" event_body="bar7"
        occurred_on="2014-06-07 13:52:06" version="2" />
    <stored_event stored_event_id="8" event_type="foo8" event_body="bar8"
        occurred_on="2014-06-07 13:52:07" version="2" />
    <stored_event stored_event_id="9" event_type="foo9" event_body="bar9"
        occurred_on="2014-06-07 13:52:08" version="2" />
    <stored_event stored_event_id="10" event_type="foo10" event_body="bar10"
        occurred_on="2014-06-07 13:52:09" version="2" />

</dataset>
